In [1]:
import numpy as np

**Valid Sudoku**

In [13]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [14]:
slice1 = s[0:3,0:3]
slice1.sum()


np.int64(45)

In [15]:
slice2 = s[0:3,3:6]
slice2

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [16]:
slice3 = s[0:3,6:9]
slice3

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [19]:
count = 0
for i in range(0,9,3):
    for j in range(0,9,3):
        sum = s[i:i+3,j:j+3].sum()
        if sum == 45:
            count = count + 1 
if count == 9:
    print("It is a valid sudoku for matrices")
else:
    print("It is not a valid sudoku for matrices")

It is a valid sudoku for matrices


In [18]:
# for row
row = np.sum(s,axis = 1)


flag = 0

for i in row:
    if i == 45:
        flag = flag + 1
    else:
        
        exit
        

# for column
col = np.sum(s,axis = 0)


for i in col:
    if i == 45:
        flag = flag + 1
    else:
        
        break

if flag == 18:
    print("Its a valid sudoku for row and column")
else:
    print("Its not a valid sudoku for either row or column")
    
 

Its a valid sudoku for row and column


In [48]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [49]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [50]:
#Find the average age of students.
age = data[:,0]
age.mean()

np.float64(18.4)

In [51]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [52]:
#Find the highest Science mark.
science = data[:,2]
science.max()

np.int64(95)

In [53]:
#Get details of the student who scored more than 90 in Math.

data[data[:,1] > 90]

array([[19, 92, 88]])

In [57]:
#Increase Math marks of all students by 5.

data[:,1] += 5
data




array([[ 18,  95,  78],
       [ 19, 102,  88],
       [ 17,  86,  95],
       [ 18,  75,  70],
       [ 20, 100,  85]])

In [77]:

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [78]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [79]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis = 0)

array([81.6, 83.2])

In [80]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [81]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])