## ARITHMETIC OPERATIONS

In [19]:
import numpy as np

In [20]:
a1 = np.array([1,2,3,4])
a2 = np.array([4,3,2,1])

In [21]:
a1 + a2 

array([5, 5, 5, 5])

In [22]:
a1 - a2

array([-3, -1,  1,  3])

In [23]:
a1 * a2

array([4, 6, 6, 4])

In [24]:
a1 / a2

array([0.25      , 0.66666667, 1.5       , 4.        ])

In [25]:
a1 // a2

array([0, 0, 1, 4])

In [26]:
a1 ** a2

array([1, 8, 9, 4])

## BROADCASTING

In [27]:
l = [12,32,4,2]
arr = np.array(l)
arr

array([12, 32,  4,  2])

In [28]:
arr + 10

array([22, 42, 14, 12])

In [29]:
arr3 = np.arange(1,26).reshape(5,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr3 * 100

array([[ 100,  200,  300,  400,  500],
       [ 600,  700,  800,  900, 1000],
       [1100, 1200, 1300, 1400, 1500],
       [1600, 1700, 1800, 1900, 2000],
       [2100, 2200, 2300, 2400, 2500]])

## DEEP AND SHALLOW COPY

In [32]:
a = np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
b = a + 10
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [36]:
a   #shallow copy no change in original

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
c = a 
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
c[0] = 23
c

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
a #deep copy original is changed that also happens in list

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
d = a.copy()     # can be made shallow copy 
d

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
d[0]= 34
d

array([34,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
a

array([23,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

##  MATRIX OPERATIONS

In [54]:
A = np.arange(1,5).reshape(2,2)
B = np.array([[1,2],[2,2]])


In [55]:
A

array([[1, 2],
       [3, 4]])

In [56]:
B

array([[1, 2],
       [2, 2]])

In [57]:
A @ B

array([[ 5,  6],
       [11, 14]])

In [58]:
A.T

array([[1, 3],
       [2, 4]])

# Advanced array manipulations

> Stacking Array

In [60]:
x = np.array([2,32,1,3])
y = np.array([7,36,3,7])

In [61]:
np.hstack((x,y))

array([ 2, 32,  1,  3,  7, 36,  3,  7])

In [62]:
np.vstack((x,y))

array([[ 2, 32,  1,  3],
       [ 7, 36,  3,  7]])

In [63]:
np.column_stack((x,y))

array([[ 2,  7],
       [32, 36],
       [ 1,  3],
       [ 3,  7]])

> Spliting Array

In [68]:
u = np.arange(1,10).reshape(3,3)
v = np.arange(10,19).reshape(3,3)

In [69]:
u

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.hsplit(u,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [72]:
np.vsplit(u,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]