In [1]:
import numpy as np

Basic Array Creation

In [3]:
arr = np.array([1,2,3,4])

In [4]:
a = [1,2,2.3,"hello"]
a

[1, 2, 2.3, 'hello']

In [5]:
np.array(a)

array(['1', '2', '2.3', 'hello'], dtype='<U32')

Vector- 1D

In [6]:
l = [[2,3,2],[3,4,2],[2,7,8]]
l

[[2, 3, 2], [3, 4, 2], [2, 7, 8]]

Matrix - 2D

In [7]:
np.array(l)

array([[2, 3, 2],
       [3, 4, 2],
       [2, 7, 8]])

Array generation funtion

In [8]:
arr = np.arange(1,15,3)
arr

array([ 1,  4,  7, 10, 13])

In [9]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr = np.ones(9)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
arr = np.linspace(1,100,40)
arr

array([  1.        ,   3.53846154,   6.07692308,   8.61538462,
        11.15384615,  13.69230769,  16.23076923,  18.76923077,
        21.30769231,  23.84615385,  26.38461538,  28.92307692,
        31.46153846,  34.        ,  36.53846154,  39.07692308,
        41.61538462,  44.15384615,  46.69230769,  49.23076923,
        51.76923077,  54.30769231,  56.84615385,  59.38461538,
        61.92307692,  64.46153846,  67.        ,  69.53846154,
        72.07692308,  74.61538462,  77.15384615,  79.69230769,
        82.23076923,  84.76923077,  87.30769231,  89.84615385,
        92.38461538,  94.92307692,  97.46153846, 100.        ])

Random Generation function

Array attributes

Array methods

Reshaping and resizing