In [2]:
import numpy as np

Indexing and Slicing of Vectors

In [4]:
arr = np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
arr[6]

np.int64(7)

In [6]:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
arr_slice1 = arr[5:11]
arr_slice1

array([ 6,  7,  8,  9, 10, 11])

In [9]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
arr[5::2]

array([ 6,  8, 10, 12, 14])

Indexing and slicing in matrix

In [3]:
arr1 = np.arange(0,30).reshape(5,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [11]:
arr1[0:2,1:3]

array([[1, 2],
       [7, 8]])

In [12]:
slice = arr1[2: ,4: ]
slice

array([[16, 17],
       [22, 23],
       [28, 29]])

In [14]:
slice_col = arr1[: , 3]
slice_col

array([ 3,  9, 15, 21, 27])

>> BOOLEAN INDEXING