In [4]:
import numpy as np

Basic Array Creation

In [3]:
arr = np.array([1,2,3,4])

In [4]:
a = [1,2,2.3,"hello"]
a

[1, 2, 2.3, 'hello']

In [5]:
np.array(a)

array(['1', '2', '2.3', 'hello'], dtype='<U32')

Vector- 1D

In [6]:
l = [[2,3,2],[3,4,2],[2,7,8]]
l

[[2, 3, 2], [3, 4, 2], [2, 7, 8]]

Matrix - 2D

In [7]:
np.array(l)

array([[2, 3, 2],
       [3, 4, 2],
       [2, 7, 8]])

Array generation funtion

In [8]:
arr = np.arange(1,15,3)
arr

array([ 1,  4,  7, 10, 13])

In [9]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr = np.ones(9)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
arr = np.linspace(1,100,40)
arr

array([  1.        ,   3.53846154,   6.07692308,   8.61538462,
        11.15384615,  13.69230769,  16.23076923,  18.76923077,
        21.30769231,  23.84615385,  26.38461538,  28.92307692,
        31.46153846,  34.        ,  36.53846154,  39.07692308,
        41.61538462,  44.15384615,  46.69230769,  49.23076923,
        51.76923077,  54.30769231,  56.84615385,  59.38461538,
        61.92307692,  64.46153846,  67.        ,  69.53846154,
        72.07692308,  74.61538462,  77.15384615,  79.69230769,
        82.23076923,  84.76923077,  87.30769231,  89.84615385,
        92.38461538,  94.92307692,  97.46153846, 100.        ])

Random Generation function

In [5]:
np.random.rand(10)


array([0.76913321, 0.00729854, 0.21925289, 0.46387634, 0.29265108,
       0.84301981, 0.43107975, 0.35597688, 0.49540944, 0.93230093])

In [6]:
np.random.randn(10)

array([ 0.3302413 , -0.18254922,  0.05793715,  0.20219621,  0.03816772,
        0.12111613, -0.62076835,  1.37030422,  0.76732394,  0.69162281])

In [7]:
np.random.randint(10,30,20)

array([29, 15, 23, 18, 12, 21, 19, 21, 13, 26, 23, 14, 21, 13, 15, 21, 10,
       17, 27, 22], dtype=int32)

Array attributes

In [10]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
arr.shape


(30,)

In [13]:
arr.size

30

In [14]:
arr.dtype

dtype('int64')

Array methods

In [15]:
arr.max()

np.int64(29)

In [16]:
arr.min()

np.int64(0)

In [17]:
arr.mean()

np.float64(14.5)

In [19]:
arr.sum()

np.int64(435)

In [22]:
arr = np.array([[3,4,3],[23,43,3],[35,3,3]])
arr

array([[ 3,  4,  3],
       [23, 43,  3],
       [35,  3,  3]])

In [23]:
arr.sum()

np.int64(120)

In [24]:
np.sum(arr,axis=0)

array([61, 50,  9])

In [25]:
arr.std()

np.float64(15.143755588800728)

In [26]:
arr.argmax()

np.int64(4)

Reshaping and resizing

In [31]:
arr.reshape(9,)

array([ 3,  4,  3, 23, 43,  3, 35,  3,  3])

In [32]:
arr.reshape(3,3)

array([[ 3,  4,  3],
       [23, 43,  3],
       [35,  3,  3]])

In [33]:
arr = arr.reshape(3,3)